#!/bin/bash

# Check if script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# Backup current resolv.conf
cp /etc/resolv.conf /etc/resolv.conf.backup

# Function to set DNS servers
set_dns() {
    echo "# Generated by change-dns script" > /etc/resolv.conf
    echo "nameserver $1" >> /etc/resolv.conf
    if [ ! -z "$2" ]; then
        echo "nameserver $2" >> /etc/resolv.conf
    fi
}

PRIMARY_DNS="178.22.122.100"
SECONDARY_DNS="185.51.200.2"

# Check if custom DNS provided
if [ $# -ge 1 ]; then
    PRIMARY_DNS=$1
fi
if [ $# -ge 2 ]; then
    SECONDARY_DNS=$2
fi

# Apply DNS changes
set_dns $PRIMARY_DNS $SECONDARY_DNS

echo "DNS servers updated successfully!"
echo "Primary DNS: $PRIMARY_DNS"
echo "Secondary DNS: $SECONDARY_DNS"